channels:
  - defaults
dependencies:
  - python=3.7
  - ipykernel
  - pip
  - pip:
    - scipy==1.1.0
    - gin-config==0.1.3
    - gym==0.12.5
    - atari-py==0.1.7
    - matplotlib
    - imageio
    - imageio-ffmpeg
    - Pillow
    - opencv-python
    - pybullet
    - pyglet
    - pyvirtualdisplay
    - tf-nightly-gpu
    - tfp-nightly
